{% set name = "gitmodules" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gitmodules-{{ version }}.tar.gz
  sha256: 27a8ea5ccb6578c8d71feb8da02d7c52f17b24a08f979c5a61f52be5c5a715bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gitmodules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kuyaki/gitmodules
  summary: Import this module to use gitmodules in Python projects without headache
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timcera
